### PR TITLE
Updated draft of the zapper contract

### PR DESCRIPTION
**Pull request by AbigailTCameron**

### CODE REVIEW

**Review by timbotro — COMMENTED** [review]
Missing flattened version of JOE zapper contract

**Comment by timbotro** [comment]
Whilst I continue to develop the tests, i've merged what i've done initially to this branch. Be sure to update your local repo with the updated remote branch. (e.g. git fetch , git pull).

You can run these tests with `npx hardhat test test/Zapper/png-zapper-tests.js`

I have found some errors with `SnowglobeZapperPangolin.sol::zapOutAndSwap()` when zapping out a large amount of LP token into asset token.

When `withdrawAmt = "60"` (line213, zapper-test.js) it fails on line 29 with : `ERC20: transfer amount exceeds balance`
image

When `withdrawAmt = "10"` it completes without issue:
image

Where is the logic that withdraws the LP token from the farm and puts it into the snowglobe? @AbigailTCameron

**Comment by timbotro** [comment]
New & improved zap out tests which now all pass:
image

Had to upgrade the test logic to have conditional paths if either leg is WAVAX

**Comment by timbotro** [comment]
@AbigailTCameron  A few issues with this:
----------------
## Changes
- Updated pkg versions. be sure to run `npm i` to install all the latest components
- Added revert tests and JOE test script to your branch. You should be able to just run `npx hardhat test test/Zapper/png-zapper-tests.js ` to replicate these issues
----------------
## Issues Found
- Cannot zap into AVAX if AVAX is not part of the original pair, e.g. PNG - LINK.e
image
- Missing Zap out AVAX feature
- `ZapInAvax` doesnt revert if min value is higher than txn amt
- `zapOut` maths doesn't seem right.  Doesn't return correct numbers for what was put in.

**Comment by AbigailTCameron** [comment]
@timbotro updated the zapInAvax function so that we can zap in if avax isn't part of the original pairing. 
Things that needs to be accounted for:
-we need something to differentiate whether or not tokenA is avax because some strats do not have avax as the first token, specifically the joe contract.

**Changes**
line 275, amt was too large that it succeeds when reaching line 60 of the zapper contract. However, we want it to fail in order for it to be reverted and so I tried the txnAmt instead.

**Review by jomarip — APPROVED** [review]
Awesome work. Shout out to @AbigailTCameron and bmino

**Review by jomarip — APPROVED** [review]

**Pull request merged**
